export const DRAWER_OPEN = 'DRAWER_OPEN';
export const DRAWER_CLOSE = 'DRAWER_CLOSE';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_DRAWER_GESTURES_ENABLED = 'SET_DRAWER_GESTURES_ENABLED';
export const SET_SPACE_INFO = 'SET_SPACE_INFO';
