# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'
plugin 'cocoapods-fix-react-native'

target 'StilInBerlin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StilInBerlin
  #
  #
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'React',
    :path => "../node_modules/react-native",
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
    ]
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'Firebase/Crash'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
  pod 'RNStoreReview', :path => '../node_modules/react-native-store-review/ios'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios'
  target 'StilInBerlinTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

