# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'SonntagsBerlin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SonntagsBerlin
  #
  #
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    # Add any other subspecs you want to use in your project
  ]
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  target 'SonntagsBerlinTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

