version: '3'
services:
          
    postgis:
        image: "mdillon/postgis"
        ports:
            - "5432:5432"
    osm_importer:
        build: ./osm_importer
        depends_on:
            - "postgis"
        command: ["/bin/bash", "-i", "/usr/local/bin/wait-for-it.sh", "-t", "60", "postgis:5432", "--", "/usr/local/bin/osm-importer.sh"]
        environment:
            - LOOP=0
            - REGION=europe/germany
            - PG_ENV_POSTGRES_DB=${POSTGRES_DB}
            - PG_ENV_POSTGRES_USER=${POSTGRES_USER}
            - PG_ENV_POSTGRES_PASSWORD=${POSTGIS_PASSWORD}
            - PG_PORT_5432_TCP_PORT=5432
            - PG_PORT_5432_TCP_ADDR=postgis
 

